# Generated by Django 4.0.2 on 2022-02-23 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_director_soundtrack_movie_directors'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='Soundtrack',
            field=models.ManyToManyField(to='api.Soundtrack'),
        ),
    ]
