# Generated by Django 4.0.2 on 2022-02-23 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_movie_soundtrack'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='Soundtrack',
            new_name='soundtracks',
        ),
    ]
